/* This is auto-generated by ll1pg.
 * Specification file: /Users/paul/Workspace/LL1-Parser-Gen/demos/arith/src/arith.spec
 * Generated at: Tue Oct 01 16:19:55 CST 2019
 * Please do NOT modify it!
 */

package arith;

import arith.Expr;
import arith.Expr.*;
import arith.error.CompileError;
import java.util.*;

public class Parser extends BaseParser
 {
    private static final int eof = 0;
    private int lookahead = -1;
    public SemValue val = new SemValue();
    
    /* tokens */
    public static final int NUM = 257; //# line 24
    
    /* search token name */
    private String[] tokens = {
        "NUM",
    };
    
    private String name(int token) {
        if (token >= 0 && token <= 256) {
            return "'" + (char) token + "'";
        } else {
            return tokens[token - 257];
        }
    }
    
    public SemValue parse() throws Exception {
        if (lookahead < 0) {
            lookahead = lex();
        }
        SemValue result = parseE();
        if (lookahead != eof) {
            throw error(name(lookahead));
        }
        return result;
    }
    
    private SemValue matchToken(int expected) throws Exception {
        SemValue self = val;
        if (lookahead == expected) {
            lookahead = lex();
        } else {
            throw error(name(lookahead), name(expected));
        }
        return self;
    }
    
    /* parsers */
    //# line 37
    private SemValue parseE1() throws Exception {
        switch (lookahead) {
            case '+':
            {
                SemValue[] params = new SemValue[4];
                params[0] = new SemValue();
                params[1] = matchToken('+');
                params[2] = parseT();
                params[3] = parseE1();
                //# line 38
                params[0].terms.add(new Term(Expr.ADD, params[2].expr));
                params[0].terms.addAll(params[3].terms);
                return params[0];
            }
            case eof:
            case ')':
            {
                SemValue[] params = new SemValue[1];
                params[0] = new SemValue();
                /* no action */
                return params[0];
            }
            default:
            {
                String[] acc = {name(Integer.valueOf('+')), name(eof), name(Integer.valueOf(')'))};
                throw error(name(lookahead), acc);
            }
        }
    }
    
    //# line 62
    private SemValue parseF() throws Exception {
        switch (lookahead) {
            case '(':
            {
                SemValue[] params = new SemValue[4];
                params[0] = new SemValue();
                params[1] = matchToken('(');
                params[2] = parseE();
                params[3] = matchToken(')');
                //# line 63
                params[0].expr = params[2].expr;
                return params[0];
            }
            case NUM:
            {
                SemValue[] params = new SemValue[2];
                params[0] = new SemValue();
                params[1] = matchToken(NUM);
                //# line 67
                params[0].expr = params[1].expr;
                return params[0];
            }
            default:
            {
                String[] acc = {name(Integer.valueOf('(')), name(NUM)};
                throw error(name(lookahead), acc);
            }
        }
    }
    
    //# line 54
    private SemValue parseT1() throws Exception {
        switch (lookahead) {
            case '*':
            {
                SemValue[] params = new SemValue[4];
                params[0] = new SemValue();
                params[1] = matchToken('*');
                params[2] = parseF();
                params[3] = parseT1();
                //# line 55
                params[0].terms.add(new Term(Expr.MUL, params[2].expr));
                params[0].terms.addAll(params[3].terms);
                return params[0];
            }
            case '+':
            case eof:
            case ')':
            {
                SemValue[] params = new SemValue[1];
                params[0] = new SemValue();
                /* no action */
                return params[0];
            }
            default:
            {
                String[] acc = {name(Integer.valueOf('*')), name(Integer.valueOf('+')), name(eof), name(Integer.valueOf(')'))};
                throw error(name(lookahead), acc);
            }
        }
    }
    
    //# line 28
    private SemValue parseE() throws Exception {
        switch (lookahead) {
            case NUM:
            case '(':
            {
                SemValue[] params = new SemValue[3];
                params[0] = new SemValue();
                params[1] = parseT();
                params[2] = parseE1();
                //# line 29
                params[0].expr = params[1].expr;
                for (Term t : params[2].terms) {
                    params[0].expr = new ArithExpr(t.op, params[0].expr, t.expr);
                }
                return params[0];
            }
            default:
            {
                String[] acc = {name(NUM), name(Integer.valueOf('('))};
                throw error(name(lookahead), acc);
            }
        }
    }
    
    //# line 45
    private SemValue parseT() throws Exception {
        switch (lookahead) {
            case NUM:
            case '(':
            {
                SemValue[] params = new SemValue[3];
                params[0] = new SemValue();
                params[1] = parseF();
                params[2] = parseT1();
                //# line 46
                params[0].expr = params[1].expr;
                for (Term t : params[2].terms) {
                    params[0].expr = new ArithExpr(t.op, params[0].expr, t.expr);
                }
                return params[0];
            }
            default:
            {
                String[] acc = {name(NUM), name(Integer.valueOf('('))};
                throw error(name(lookahead), acc);
            }
        }
    }
    
}
/* end of file */
